.env.testnet.example, README.md, package.json
=> :memo: update env example

pages/index.tsx
=> :lipstick: Make log section take half of the screen

components/MnemonicModal.tsx
=> :lipstick: Add spacing to mnemonic inputs

components/BotForm.tsx, components/MnemonicModal.tsx, components/disconnectWallet.tsx, components/validateWallet.tsx
=> Issue 38 fix on passcode entry screen lock icon should be centered with title and remove scroll bars

components/BotForm.tsx
=> Issue 37 fix update the tooltips on the form

components/BotForm.tsx, lib/runLoop.ts, themes/normal.js
=> Issue 49 fix update stop bot button color

components/AssetSearchInput.tsx, components/BotForm.tsx, components/CustomTextInput.tsx, lib/helper.ts, package.json, yarn.lock
=> :sparkles: AssetId suggestions

components/BotForm.tsx, components/CustomRangeSlider.tsx, tsconfig.json
=> Issue 30 fix ensure the sliders have the right minimum value

components/BotForm.tsx, tsconfig.json
=> :bug: link view in algodex with the asset id

components/BotForm.tsx
=> :zap: Update note base on user input

components/AssetSearchInput.tsx, components/BotForm.tsx, components/MnemonicModal.tsx, components/disconnectWallet.tsx, components/validateWallet.tsx, components/walletButton.tsx, lib/helper.ts
=> :zap: Display wallet balance

components/CustomPasswordInput.tsx, components/MnemonicModal.tsx, components/validateWallet.tsx
=> :bug: Add autoComplete to password inputUpdate stop button

components/CustomPasswordInput.tsx
=> :bug: Add "name" to password input

components/BotForm.tsx, components/MnemonicModal.tsx, components/disconnectWallet.tsx, components/walletButton.tsx
=> :zap: Unlock wallet on page load

.gitignore, components/BotForm.tsx, components/MnemonicModal.tsx, components/disconnectWallet.tsx, components/walletButton.tsx
=> Issue 25 fix remove log and ldb files from git and add them to gitignore

bin/bot.ts, components/BotForm.tsx, components/CustomPasswordInput.tsx, lib/bot.ts, lib/runLoop.ts
=> Issue 54 fix bot environment variables should be base on what user selects on the g UI

components/BotForm.tsx, components/CustomPasswordInput.tsx, components/CustomTextInput.tsx, components/validateWallet.tsx, themes/normal.js
=> :bug: Disable button if not enough asa or balance

components/BotForm.tsx, components/validateWallet.tsx, hooks/usePriceConversionHook.tsx, lib/helper.ts
=> :sparkles: $100 minimum to qualify

components/BotForm.tsx, components/MnemonicModal.tsx, lib/helper.ts
=> :sparkles: verify mnemonics on import

components/LogOutput.tsx
=> Issue 78 fix log box should also auto size and take up half the screen size

components/LogOutput.tsx
=> :zap: Update log output autoscroll

components/BotForm.tsx
=> :sparkles: Increase spread percentage limit

components/AssetSearchInput.tsx, components/BotForm.tsx, lib/helper.ts
=> :bug: fetch assets from mainnet when env is

components/AssetSearchInput.tsx
=> Issue 72 fix add placeholder “asset id” to dropdown to choose assets

components/BotForm.tsx
=> :bug: Display balance of selected assets only

components/BotForm.tsx, components/CustomTextInput.tsx, components/LogOutput.tsx, lib/helper.ts
=> Issue 42 feature add advanced option to auto delete old log messages

components/BotForm.tsx, lib/helper.ts
=> :zap: check if asset is on tinyman

components/BotForm.tsx
=> Issue 70 fix format algo input values with commas

.env.testnet.example, bin/bot.ts, components/BotForm.tsx, hooks/usePriceConversionHook.tsx, lib/bot.ts, lib/convertToDBObject.spec.js, lib/convertToDBObject.ts, lib/getCancelPromises.ts, lib/getCurrentOrders.spec.js, lib/getCurrentOrders.ts, lib/getCurrentState.spec.js, lib/getCurrentState.ts, lib/getEscrowsToCancelAndMake.ts, lib/getPlannedOrderChanges.ts, lib/placeOrdersAndUpdateDB/addOrdersToDB.spec.js, lib/placeOrdersAndUpdateDB/addOrdersToDB.ts, lib/placeOrdersAndUpdateDB/placeOrders.ts, lib/placeOrdersAndUpdateDB/placeOrdersAndUpdateDB.ts, lib/placeOrdersAndUpdateDB/waitForOrders.ts, lib/runLoop.ts, package.json, yarn.lock
=> :bug: Stop bot when there is an internal error

components/BotForm.tsx, components/LogOutput.tsx, lib/runLoop.ts
=> :bug: Made order size and spread percentage a log scale

components/BotForm.tsx, lib/helper.ts, lib/runLoop.ts
=> Issue 76 feature bot does not lookup tinyman liquidity or if asset is on tinyman

components/BotForm.tsx, hooks/usePriceConversionHook.tsx, lib/helper.ts
=> :sparkles: Display usd equivalents

components/BotForm.tsx, components/walletButton.tsx
=> Issue 101 fix don’t allow wallet to be cleared if bot is running

components/LogOutput.tsx, lib/storage.ts
=> :zap: Autodelete should default to 1000 and settings cached

components/BotForm.tsx, lib/runLoop.ts
=> Issue 99 fix when canceling orders should say “canceling orders”

lib/placeOrdersAndUpdateDB/placeOrders.ts, lib/runLoop.ts
=> Issue 100 fix problem in logs where it says all orders are “buy”orders needs to change to“sell” for sell orders

components/AssetSearchInput.tsx, components/BotForm.tsx
=> Issue 102 chore switching from testnet to mainnet should clear out logs

components/Layout.tsx, pages/index.tsx
=> :lipstick: Update layout width and padding

components/BotForm.tsx, components/LogOutput.tsx, lib/cancelOrders.ts, lib/placeOrdersAndUpdateDB/placeOrders.ts, lib/placeOrdersAndUpdateDB/waitForOrders.ts, lib/runLoop.ts
=> :construction: Stop bot automatically if error

components/BotForm.tsx, components/LogOutput.tsx, lib/placeOrdersAndUpdateDB/waitForOrders.ts
=> :bug: Fix log slider's smoothness

components/BotForm.tsx, lib/placeOrdersAndUpdateDB/placeOrders.ts
=> :bug: Fix stopbot function

components/BotForm.tsx, components/walletButton.tsx
=> Issue 118 fix if i click outside the unlock password modal it incorrectly makes the modal go away

components/BotForm.tsx, components/walletButton.tsx
=> Issue 123 feature default order size to 300 algos

components/BotForm.tsx
=> Issue 125 fix spread percentage slider should have more granularity smoother in slider

components/BotForm.tsx, components/CustomTextInput.tsx
=> Issue 121 fix it won t let me delete the % spread

components/BotForm.tsx, components/LogOutput.tsx, lib/runLoop.ts
=> Issue 128 fix delete logs setting should be based on lines that have at least a length of 1 character   ignore blank lines

components/BotForm.tsx, components/LogOutput.tsx
=> Issue 124 fix user should be able to input decimal numbers in the input box   right now it only allows integer entries

.vscode/launch.json, components/BotForm.tsx
=> fix off by 100x error for percentages

components/BotForm.tsx
=> Fix asset balance issue with decimals

components/BotForm.tsx, components/CustomNumberFormatter.tsx
=> Issue 122 fix use local formatting for number for order size

components/BotForm.tsx, components/CustomNumberFormatter.tsx
=> Issue 140 fix when i unlock the bot the start button is green even though i didn t select an asset

components/AssetSearchInput.tsx, components/BotForm.tsx, hooks/usePriceConversionHook.tsx, lib/getTinyman.ts, lib/helper.ts, lib/initAPI.spec.js, lib/initAPI.ts
=> :zap: Fix USD prices

components/AssetSearchInput.tsx, components/MnemonicModal.tsx
=> Issue 133 feature add a checkbox to agree to disclaimer that algodex is not responsible for lost funds

components/BotForm.tsx, lib/helper.ts, lib/placeOrdersAndUpdateDB/placeOrders.ts, lib/placeOrdersAndUpdateDB/placeOrdersAndUpdateDB.ts, lib/runLoop.spec.js, lib/runLoop.ts
=> :bug: Fix infinite loop when balance is low

.gitignore, lib/getLatestPrice.ts, lib/helper.ts
=> :bug: Fix mainnet bug

lib/initAPI.ts, next.config.js
=> :bug: Update mainnet proxy

lib/getLatestPrice.ts, lib/getOpenAccountSetFromAlgodex.ts, lib/helper.ts, lib/initAPI.spec.js, lib/initAPI.ts, lib/runLoop.ts, next.config.js
=> Issue 170 acceptance switch to use algodex v2 sdk for testnet

components/BotForm.tsx, lib/helper.ts
=> :construction: Detect trade on new tab

components/BotForm.tsx, components/Layout.tsx, components/Logo.tsx, components/Nav/Drawer.tsx, components/Nav/Link.tsx, components/Nav/ListItemLink.tsx, components/Nav/Toolbar.tsx
=> :sparkles: nav links and mobile sidebar

components/BotForm.tsx, components/Reducer/updateReducer.tsx, lib/helper.ts
=> :sparkles: Implement useReducer

components/BotForm.tsx, components/Reducer/updateReducer.tsx, lib/helper.ts, themes/normal.js
=> Issue 176 feature display asset s current price

components/BotForm.tsx, components/LogOutput.tsx, context/appContext.tsx, lib/cancelAssetOrders.ts
This PR represents working functionality for querying and cancelling of orders by wallet address and asset id.
- Dynamically change asset Id and cancel all orders related to asset ID and wallet address
- Simple example of a callback function for alerting the UI of the state of cancelling
- Add a alert message module like `toast` to improve the quality of the callbackFN 
#162
=> Issue 162 feature cancel all orders for trading pair

components/BotForm.tsx
=> Issue 180 fix instant validation

components/BotForm.tsx
=> :bug: Link market URL directly to the asset

components/LogOutput.tsx
=> :loud_sound: Include datetime in logs

components/LogOutput.tsx
=> :bug: Indicate bot cancels open orders only for d selected asset

components/BotForm.tsx, components/Form/AssetSearchInput.tsx, context/appContext.tsx, lib/helper.ts, next.config.js
=> :zap: distinguish environment by the url path

README.md, bin/bot.ts, context/appContext.tsx, lib/bot.ts
=> :zap: Update cli args to include more options

components/Modals/MnemonicModal.tsx
=> Issue 199 fix minor grammar improvement

components/AvailableBalance.tsx, components/BotForm.tsx, components/HtmlTooltip.tsx
=> :bug: update

components/BotForm.tsx, components/Note.tsx
=> :lipstick: Update note content and icon

components/BotForm.tsx, components/Form/AssetSearchInput.tsx, components/Note.tsx
=> Issue 208 fix make verified icons for assets look larger

components/BotForm.tsx, components/Form/AssetSearchInput.tsx, components/Reducer/updateReducer.tsx
=> :bug: Ensure immediate form validation

bin/bot.ts, lib/bot.ts
=> :bug: Remove ORDER_ALGO_DEPTH check

components/footer.tsx
=> Footer design updated

components/LogOutput.tsx
=> :lipstick: made log setting fit content

components/BotForm.tsx
=> :bug: Fix button status when bot stops

components/BotForm.tsx, components/Reducer/updateReducer.tsx, lib/helper.ts, lib/runLoop.ts, lib/storage.ts
=> :zap: Notify if there is an open trade on same asset

components/BotForm.tsx, components/LogOutput.tsx, context/appContext.tsx, hooks/useFormik.tsx
=> :bug: disable button if no asset id

components/BotForm.tsx, components/Layout.tsx, components/LogOutput.tsx, context/appContext.tsx, hooks/useFormik.tsx
=> Issue 222 fix docs page should link to trading bot docs

components/AvailableBalance.tsx, components/LogOutput.tsx, components/OpenOrders/orderRow.tsx, components/OpenOrders/ordersTable.tsx, context/appContext.tsx, lib/cancelAssetOrders.ts
=> :sparkles: Display all open orders for the selected asset

.env.testnet.example, README.md, bin/bot.ts, lib/bot.ts
=> :memo: Include nearestNeighbor in cli variables and Update readme

README.md
=> :memo: Include spreadPercentage sample in readme
